### PR TITLE
use public git address

### PR DESCRIPTION
**Pull request by malles**
To avoid:

```
Cloning into 'Mailqueue'...
The authenticity of host 'github.com (192.30.252.128)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? y
Please type 'yes' or 'no': yes
Warning: Permanently added 'github.com,192.30.252.128' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
```

### CODE REVIEW

**Comment by floriandotpy** [comment]
Thanks! 

Small disclaimer before you start using the module though: I've recently noticed timeouts for larger queues. I'll need to figure out how to send bulk messages with a single smtp request. So just make sure you test with your own smtp settings before using it in production.

**Comment by malles** [comment]
Well, to be honest, I'm playing around with Cockpit and custom Addons, and using your code for uhm.. inspiration :)
Love Cockpit!

**Comment by malles** [comment]
OT SMTPmailer even sends a mail with eg 2 receivers, a cc and 2 bcc's as 5 seperate mails. I quess that is the it should be/must be.
I like the idea of the mailqueue though!

**Comment by floriandotpy** [comment]
Awesome, that's what this code was for anyway. (Not claiming this is the perfect way to create a custom module, but I hope it's a way to start the discussion)

**Pull request merged**
